version: '3'
services:

  #PHP Service
  app-current:
    image: srgptk/tetlv:app
    container_name: app-current
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-current
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.php/local.ini:/usr/local/etc/php/conf.d/local.ini


  #Nginx Service
  webserver-current:
    image: srgptk/tetlv:webserver
    container_name: webserver-current
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - ./:/var/www
      - ./.nginx/conf.d/:/etc/nginx/conf.d/


  #MySQL Service
  db-current:
    image: srgptk/tetlv:db
    container_name: db-current
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql/
      - ./.mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "5455:3306"
    environment:
      MYSQL_DATABASE: 'symfony'
      MYSQL_USER: 'symfony_user'
      MYSQL_PASSWORD: 'symfony@secret'
      MYSQL_ROOT_PASSWORD: 'very@secret#mysql%password'
      SERVICE_TAGS: 'dev'
      SERVICE_NAME: 'mysql'

#Volumes
volumes:
  dbdata:
    driver: local
